[package]
name = "example_wrangle_processchunk_iterate_paths"
version = "0.1.0"
authors = ["Stewart Mackenzie <setori88@gmail.com>"]

[lib]
name = "example_wrangle_processchunk_iterate_paths"
crate-type = ["dylib"]

[dependencies]
capnp = "*"
rustfbp = "*"
