[package]
name = "example_wrangle_processchunk_extract_keyvalue"
version = "0.1.0"
authors = ["test <test@test.com>"]

[lib]
name = "example_wrangle_processchunk_extract_keyvalue"
crate-type = ["dylib"]

[dependencies]
capnp = "*"
rustfbp = "*"
