[package]
name = "example_wrangle_processchunk_convert_json_vector"
version = "0.1.0"
authors = ["Stewart Mackenzie <setori88@gmail.com>"]

[lib]
name = "example_wrangle_processchunk_convert_json_vector"
crate-type = ["dylib"]

[dependencies]
capnp = "*"
rustfbp = "*"
rustc-serialize = "*"
